### ISSUE TITLE
TODO es una query

### ISSUE THREAD

**Issue by YanRH80** [tairh80/Lan4#1]
#Pénfigo

- Pénfigo = Enfermedad.Ampollosa, Depósito(Ig/Intraepidérmico), Afecta(Unión.Intercelular), !Nikolsky
- Pénfigo.Vulgar = Enfermedad.Ampollosa(Sí), Autoinmunidad(Sí) 
- Pénfigo = Ampolla(Subepidérmica)
- IgA = [[Dapsona]]

- - -

Realmente las comas sirven para separar celdas y nada más. A la izquierda va LO QUE SEA que esté en el inicio de la columna, y la derecha se define por la lista de las variables, cuyo contenido se define por los paréntesis. Si no hay paréntesis, simplemente es una variable TRUE/FALSE.

**Comment by khachimarur80** [comment]
El !Nikolsky se escribe usando una variable Nikolsky(No). Para la Enfermedad.Ampollosa, se creará a posteriori una nueva taxonomía dónde se incluye Pénfigo
